apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "GuaranteedSubscriber"
  annotations:
    github.com/project-slug: undefined/undefined
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/opthomas"
